# Generated by Django 6.0.6 on 2026-06-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
